### ISSUE TITLE
socket.io error.

### ISSUE THREAD

**Issue by karthikbr82** [thoqbk/rewebrtc#2]
I am trying to build the app, but am getting this error from socket.io, Have you come across this error before? Any Help appreciated to fix this.

cannot find variable document
doPoll

More details in the attached screenshot.

![screenshot_20170329-181559](https://cloud.githubusercontent.com/assets/12692403/24462255/341877b0-14ac-11e7-92ca-3c9779e1ffdb.png)

**Comment by thoqbk** [comment]
@karthikbr82 I found the solution in this link and updated my code. Can you check? https://github.com/oney/react-native-webrtc/issues/30

**Comment by karthikbr82** [comment]
@thoqbk I think there was some issue with my packager, it works without setting UA string. Thanks.
